# run: conda env create --file requirements.yml
name: ORGANIC
channels:
- defaults
- conda-forge
- rdkit
- matsci
dependencies:
- python=3.6.1
- anaconda
- jupyter
- numpy
- scipy
- pandas
- rdkit
- tensorflow==1.0
- keras
- pymatgen
- dill
- pip
- pip:
  - tqdm
  - keras_tqdm
